const PREFIX = "MAIN_";

export const SIGN_IN_REQUEST = `${PREFIX}SIGN_IN_REQUEST`;
export const SIGN_IN_SUCCESS = `${PREFIX}SIGN_IN_SUCCESS`;
export const SIGN_IN_FAIL = `${PREFIX}SIGN_IN_FAIL`;

export const SIGN_UP_REQUEST = `${PREFIX}SIGN_UP_REQUEST`;
export const SIGN_UP_SUCCESS = `${PREFIX}SIGN_UP_SUCCESS`;
export const SIGN_UP_FAIL = `${PREFIX}SIGN_UP_FAIL`;
