const PREFIX = "MAIN_";

export const ADD_FOOD = `${PREFIX}ADD_FOOD`;

export const BOOKING_TICKETS_REQUEST = `${PREFIX}BOOKING_TICKETS_REQUEST`;
export const BOOKING_TICKETS_SUCCESS = `${PREFIX}BOOKING_TICKETS_SUCCESS`;
export const BOOKING_TICKETS_FAIL = `${PREFIX}BOOKING_TICKETS_FAIL`;
