const PREFIX = "MAIN_";

export const FETCH_ALL_MOVIES_REQUEST = `${PREFIX}FETCH_ALL_MOVIES_REQUEST`;
export const FETCH_ALL_MOVIES_SUCCESS = `${PREFIX}FETCH_ALL_MOVIES_SUCCESS`;
export const FETCH_ALL_MOVIES_FAIL = `${PREFIX}FETCH_ALL_MOVIES_FAIL`;

export const CHANGE_SHOWING_OPTION = `${PREFIX}CHANGE_SHOWING_OPTION`;
