const PREFIX = "MAIN_";

export const FETCH_MOVIE_DETAIL_REQUEST = `${PREFIX}FETCH_MOVIE_DETAIL_REQUEST`;
export const FETCH_MOVIE_DETAIL_SUCCESS = `${PREFIX}FETCH_MOVIE_DETAIL_SUCCESS`;
export const FETCH_MOVIE_DETAIL_FAIL = `${PREFIX}FETCH_MOVIE_DETAIL_FAIL`;

export const CHANGE_SHOW_TIME_OPTION = `${PREFIX}CHANGE_SHOW_TIME_OPTION`;
export const GET_ID_SHOW_TIME_SELECTED = `${PREFIX}GET_ID_SHOW_TIME_SELECTED`;
