const PREFIX = "MAIN_";

export const CHOOSE_MOVIE_FILTER = `${PREFIX}CHOOSE_MOVIE_FILTER`;
export const CHOOSE_THEATER_FILTER = `${PREFIX}CHOOSE_THEATER_FILTER`;
export const CHOOSE_DATE_FILTER = `${PREFIX}CHOOSE_DATE_FILTER`;
export const CHOOSE_HOUR_FILTER = `${PREFIX}CHOOSE_HOUR_FILTER`;

export const FETCH_ALL_MOVIES_REQUEST = `${PREFIX}FETCH_ALL_MOVIES_REQUEST`;
export const FETCH_ALL_MOVIES_SUCCESS = `${PREFIX}FETCH_ALL_MOVIES_SUCCESS`;
export const FETCH_ALL_MOVIES_FAIL = `${PREFIX}FETCH_ALL_MOVIES_FAIL`;

export const CHANGE_SHOWING_OPTION = `${PREFIX}CHANGE_SHOWING_OPTION`;
