const PREFIX = "MAIN_";

export const FETCH_MOVIE_DETAIL_REQUEST = `${PREFIX}FETCH_MOVIE_DETAIL_REQUEST`;
export const FETCH_MOVIE_DETAIL_SUCCESS = `${PREFIX}FETCH_MOVIE_DETAIL_SUCCESS`;
export const FETCH_MOVIE_DETAIL_FAIL = `${PREFIX}FETCH_MOVIE_DETAIL_FAIL`;
