const PREFIX = "MAIN_";

export const FETCH_ALL_MOVIES_REQUEST = `${PREFIX}FETCH_ALL_MOVIES_REQUEST`;
export const FETCH_ALL_MOVIES_SUCCESS = `${PREFIX}FETCH_ALL_MOVIES_SUCCESS`;
export const FETCH_ALL_MOVIES_FAIL = `${PREFIX}FETCH_ALL_MOVIES_FAIL`;

export const VIEW_TRAILER = `${PREFIX}VIEW_TRAILER`;
export const IS_OPEN_VIDEO_TRAILER = `${PREFIX}IS_OPEN_VIDEO_TRAILER`;

export const CHANGE_SHOWING_OPTION = `${PREFIX}CHANGE_SHOWING_OPTION`;
