const PREFIX = "MAIN_";

export const FETCH_SHOW_TIME_DETAIL_REQUEST = `${PREFIX}FETCH_SHOW_TIME_DETAIL_REQUEST`;
export const FETCH_SHOW_TIME_DETAIL_SUCCESS = `${PREFIX}FETCH_SHOW_TIME_DETAIL_SUCCESS`;
export const FETCH_SHOW_TIME_DETAIL_FAIL = `${PREFIX}FETCH_SHOW_TIME_DETAIL_FAIL`;

export const GET_SELECTED_SEATS = `${PREFIX}GET_SELECTED_SEATS`;

export const CLEAR_SHOW_TIME_DETAIL = `${PREFIX}CLEAR_SHOW_TIME_DETAIL`;
